import "./globals.css"
import NavbarCustom from "@/components/Navbar"
import { Providers } from "./providers"

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='dark'>
      
      <body>
        <NavbarCustom/>
        {children}
      </body>
    </html>
  )
}
